* 计算机方面的名言警句
  #+BEGIN_QUOTE
  Any fool can write code that a computer can u nderstand. Good programmer write code that humans can understand.
  -- Martin Fowler
  #+END_QUOTE

  #+BEGIN_QUOTE
  You think you know when you learn, are more sure when  you can write, even more when you can teach, but certain when you can program.
  -- Alan Perlis(Yale University computer scientist)
  #+END_QUOTE

  #+BEGIN_QUOTE
  Make it run, make it right, make it fast
  --Butler Lampson
  #+END_QUOTE

  #+BEGIN_QUOTE
  The best writing is rewriting
  --E. B. White
  #+END_QUOTE

  #+BEGIN_QUOTE
  Programs must be written for people to read, and only incidentally for machines to execute.
  -- Abelson & Sussman, SICP, preface to the first edition
  #+END_QUOTE

  #+BEGIN_QUOTE
  A man is a success if he get up in the morning and get to bed at night and in between he does what he wants to do

  -- Bob Dylan
  #+END_QUOTE
  #+BEGIN_QUOTE
  Emacs outshines all other editing software in approximately the same way that the noonday sun does the stars. It is not just bigger and brighter; it simply makes everything else vanish.
  -Neal Stephenson, “In the Beginning was the Command Line”
  #+END_QUOTE

  #+BEGIN_QUOTE
  Most people just make the mistake that is should be simple to design simple things. In reality, the effort required to design something is inversely proportional to the simplicity of the result.
  -- Roy Fileding
  #+END_QUOTE
