#+TITLE: 个人Vim配置过程说明
#+DATE: <2013-08-01 Thu>
#+AUTHOR: 荣怡
#+EMAIL: sqrongyi@163.com
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:{} arch:headline
#+OPTIONS: author:t c:nil creator:comment d:(not LOGBOOK) date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t toc:t todo:t |:t
#+CREATOR: Emacs 24.3.1 (Org mode N/A)
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE: en
#+SELECT_TAGS: export


  

* 配置过程
  之前配置Vim一般会有个 =~/.vim= 文件夹来存放各种插件。然后手动拷贝，比较麻烦。后来有Vim版的tarball然后直接打开Vim执行个命令就可以安装插件， =git= 出现之后开发模式变了，Vim配置方面也有点变化，出现了基于 =Git= 的插件配置方法。主要是基于这两个插件[[https://github.com/tpope/vim-pathogen][vim-pathogen]] 以及[[https://github.com/windelicato/dotfiles][vundle]] ，它们的主要区别是 =vim-pathogen= 在安装/卸载新插件时只是自己手动的去 =git clone= 以及手动删除对应插件的文件夹 ，而 =vundle= 则需要修改 =.vimrc= 文件，我选择的是基于 =vim-pathogen= 的Vim配置。因为 *最终* 发现 =vim-pathogen= 要更为方便一些。下文详细叙述 *基于vim-pathogen* 的各插件安装过程以及插件的说明。

  
* vim-pathogen

  首先备份你的 =.vimrc= 以及 =.vim/= 文件。
  执行下列命令：
  #+BEGIN_SRC bash
  # create nessary dir
  mkdir -p .vim/{autoload,bundle}
  # get vim-pathogen
  git clone https://github.com/tpope/vim-pathogen.git /tmp/vim-pathogen
  # copy pathogen.vim to vim autoload dir
  cp /tmp/vim-pathogen/autoload/pathogen.vim ~/.vim/autoload
  #+END_SRC

  然后修改 =.vimrc= 文件添加以下内容到配置文件顶部:

  #+BEGIN_SRC bash
  execute pathogen#infect()
  syntax on
  filetype plugin indent on
  #+END_SRC

  至此管理插件的插件 =vim-pathogen= 安装成功。
  后续插件的安装大部分只是简单的 =git clone= 到 =.vim/bundle= 文件夹即可。



* [[https://github.com/Valloric/YouCompleteMe][YouCompleteMe]]
  插件功效： 代码补全
  有用过Eclipse开发C一段时间因为Vim的补全实在令人沮丧，所以折衷的方案是在Eclipse里安装Vim插件。后来发现这款插件，我又回来了。
  我无法掩盖我对这款插件的推崇，所以我把它放在第一位来讲。

  因为YCM需要较高版本vim的支持，所以最好编译安装最新版本的vim这在官方的wiki里有详细的安装说明。
  编译新版本Vim在[[https://github.com/Valloric/YouCompleteMe/wiki/Building-Vim-from-source][官方wiki]] 有详细的说明，其首页有详细的安装步骤，这里不赘述。

* [[https://github.com/chriskempson/tomorrow-theme][Tomorrow Theme]]
  插件功效: 主题配色

  之前一直用desert主题，后来厌倦了，换了这个Tomorrow主题，用的是其中白色的一款，后来对这个主题也小小的疲倦了，换其他的主题，失败了，因为换不过去了！真心觉得赏心悦目。主题的安装和其他的插件有些不同，直接放在 =.vim/colors= 文件夹里即可。

  
  #+BEGIN_SRC bash
    https://github.com/mileszs/ack.vim.git
    https://github.com/vim-scripts/Auto-Pairs.git
    https://github.com/kien/ctrlp.vim.git
    https://github.com/vim-scripts/c.vim.git
    https://github.com/othree/html5.vim.git
    https://github.com/Valloric/ListToggle.git
    https://github.com/Valloric/MatchTagAlways.git
    https://github.com/scrooloose/nerdtree
    https://github.com/Valloric/python-indent.git
    https://github.com/vim-scripts/restore_view.vim.git
    https://github.com/scrooloose/syntastic.git
    https://github.com/majutsushi/tagbar.git
    https://github.com/vim-scripts/taglist.vim.git
    https://github.com/tomtom/tcomment_vim.git
    https://github.com/hail2u/vim-css3-syntax.git
    https://github.com/ap/vim-css-color.git
    https://github.com/Lokaltog/vim-easymotion.git
    https://github.com/tpope/vim-fugitive.git
    https://github.com/Valloric/vim-indent-guides.git
    https://github.com/Lokaltog/vim-powerline.git
    https://github.com/tpope/vim-sensible.git
    https://github.com/tpope/vim-surround.git
    https://github.com/Valloric/xmledit.git
    https://github.com/Valloric/YouCompleteMe.git
  #+END_SRC

  
  全部clone放 =./vim/bundle= 下即可，遵照各自的安装说明就好
  
